### ISSUE TITLE
【BUG】未标记精彩时刻的视频仍然会出现精彩时刻按钮

### ISSUE THREAD

**Issue by Aarondongsq** [hanydd/BilibiliSponsorBlock#101]
如题，希望修复

**Comment by Aarondongsq** [comment]
补充：片段刚刚提交精彩时刻后，按钮有时不会出现，而刷新后又出现

**Comment by hanydd** [comment]
fixed by 801f03c79d79d49ed26960e8dc901fdeb157b8da

**Comment by Aarondongsq** [comment]
新问题：绑定了精彩时刻的视频有时候不会显示跳过按钮，插件刷新无用，只有浏览器刷新才显示
