### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by sj-3-sj** [hanydd/BilibiliSponsorBlock#109]
## 问题描述  
简要描述您遇到的 Bug 或错误：音乐视频总是莫名其妙自动跳过既不是静音片段，也不是广告的片段，并且跳过后还给我提示是否提交
而且我全部都设置成的手动跳过，还是自己跳
## 复现步骤  
请提供详细的复现步骤：没有任何操作，插件自己操作的

1. 打开网址：https://www.bilibili.com/video/BV13FBEYgEfT/?vd_source=2f49e51e59b40adf51e355c86d7dfb20
2. 
3. 

## 预期表现  
描述您期望的正确表现：不要莫名其妙跳过

## 实际表现  
描述目前实际出现的错误或不符合预期的行为：自动跳过非广告片段

## 屏幕截图或录像  
如果可能，请附上相关截图或视频，以便更好地说明问题：

## 运行环境  
- 操作系统（OS）：win11
- 浏览器：edge
- 浏览器版本：最新
- 插件版本：最新

## 其他信息  
补充任何相关信息或日志：

**Comment by xiaoxuan010** [comment]
请尝试在插件`选项页面 > 实验功能`中关闭以下两个选项：
- 匹配成功后自动跳过
- 匹配成功后打开提交窗口
