### ISSUE TITLE
【小请求】支持bilibili.tv（哔哩哔哩国际版）的视频

### ISSUE THREAD

**Issue by Aarondongsq** [hanydd/BilibiliSponsorBlock#110]
# 前提概要
哔哩哔哩分为两个版本，即：
1. **哔哩哔哩**（bilibili.com）：国内版本的哔哩哔哩
2. **BiliBili（哔哩哔哩海外版）** （bilibili.tv）：海外版本的哔哩哔哩，界面英文
我想，它们两个都是属于B站，我希望可以兼容哔哩哔哩海外版，可以在海外版提交片段

# 具体是如何实现呢？
与原版一样，操作逻辑也是一样的，只不过“片段提交”按钮和“精彩时刻"按钮要做一些调整，下面是一张哔哩哔哩海外版的截图，方便查看布局：
![image](https://github.com/user-attachments/assets/bbd9d303-66b6-4978-b7d0-1e5e09db485e)

**Comment by etherfun** [comment]
稍微看了一眼 差距有点大而且好像没有适配的必要?
 - 海外版好像屏蔽国内访问(我这直接打开就是一个空白页
 - 两边数据好像不互通 海外版使用av号但是没有开头的av 添加av然后国内版搜索是无效的 使用额外的插件搜索则可以找到视频但是无法观看
 - 现在只能使用bv号提交和获取片段 但是海外版只有av号

**Comment by Aarondongsq** [comment]
> 稍微看了一眼 差距有点大而且好像没有适配的必要?
> 
> * 海外版好像屏蔽国内访问(我这直接打开就是一个空白页
> * 两边数据好像不互通
> * 现在只能使用bv号提交和获取片段 但是海外版的类似av号的一串数字没办法转为bv号

想了想也是，用bilibili海外版的人确实不多，用了那啥啥去了国外第一时间也是看YouTube，没人在意海外版bilibili
将会关闭此Issues为”未计划“
