### ISSUE TITLE
[Feature] 对于某些up视频进行批量操作跳过片头（固定时长）

### ISSUE THREAD

**Issue by yeweiyuni** [hanydd/BilibiliSponsorBlock#112]
## 功能描述  
[Feature] 对于某个up视频批量操作跳过片头（固定时长），像快速跳过固定时长，固定模版快速提交（当前提交步骤无记忆功能）

## 使用场景  
某些up的固定开头，或者固定恰饭时间段

**Comment by xiaoxuan010** [comment]
与 #10 重复了。
