### ISSUE TITLE
在使用列表播放时不能运作

### ISSUE THREAD

**Issue by esclm** [hanydd/BilibiliSponsorBlock#18]
## 描述

在 https://www.bilibili.com/list/ 下看视频，插件功能不能实现。

观看“全部视频”或者“合集和列表”都会使用 list 

## 使用环境

- 插件版本：0.2.5
- 浏览器：Chrome 124.0.6367.119

**Comment by du33169** [comment]
绑定搬运视频功能在列表播放时仍不可用，版本0.2.8

**Comment by hanydd** [comment]
Fixed by https://github.com/hanydd/BilibiliSponsorBlock/commit/ef02569b1410c135990532a09f318062de037590
