### ISSUE TITLE
跳过片段的质量不稳定

### ISSUE THREAD

**Issue by wc7086** [hanydd/BilibiliSponsorBlock#20]
如视频 BV1aD421M71A 有一大截广告没跳过，我自己提交片段仍然被该片段覆盖。

建议点踩多于点赞的片段将被最新提交的片段直接覆盖。

**Comment by hanydd** [comment]
目前已经有优先显示高赞片段的逻辑了，不过如果两个片段点赞差距不大的话，显示的概率都比较大。
我可以先手动隐藏不够精确的片段。如果下次有类似的问题，可以在Q群371384235里直接发出来，管理员可以手动隐藏。

**Comment by hanydd** [comment]
#21
