### ISSUE TITLE
播放列表無綁定YT的按鈕

### ISSUE THREAD

**Issue by NeKoOuO** [hanydd/BilibiliSponsorBlock#23]
![image](https://github.com/user-attachments/assets/e533ad74-8a5b-4470-81a9-205e9490a06f)

**Comment by hanydd** [comment]
#18

**Comment by hanydd** [comment]
Fixed by https://github.com/hanydd/BilibiliSponsorBlock/commit/ef02569b1410c135990532a09f318062de037590
