### ISSUE TITLE
恰饭片段的补偿机制?

### ISSUE THREAD

**Issue by Ocyss** [hanydd/BilibiliSponsorBlock#25]
> 不知道会不会影响恰饭收益， 不会就算了🥲

感觉有两种方案：
1. 跳过片段，视频播放完自动投币 
2. 跳过片段，用其他方式实现后台隐藏播放

也能根据播放的占比  `观看时间 / (总时长 - 跳过片段) > ??%`  进行操作？

**Comment by Colerar** [comment]
网页端用户比例微乎其微，没有这种担心的必要。
