### ISSUE TITLE
开发Tampermonkey插件

### ISSUE THREAD

**Issue by JunFengLi666** [hanydd/BilibiliSponsorBlock#26]
请问大佬能不能开发Tampermonkey插件，感觉chrome插件太耗资源了

**Comment by hanydd** [comment]
你指的是消耗什么资源呢？油猴插件不会比浏览器插件更节省资源吧

**Comment by NeKoOuO** [comment]
> 请问大佬能不能开发Tampermonkey插件，感觉chrome插件太耗资源了

這東西純屬吃力不討好沒什麼必要 而且這本來就是個移植項目 原項目本來就不是Tampermonkey的

**Comment by hanydd** [comment]
> 這東西純屬吃力不討好沒什麼必要 而且這本來就是個移植項目 原項目本來就不是Tampermonkey的
> 
> 

我能想到的唯一优点是大陆的chrome上安装和更新比较方便，因为chrome貌似装不了edge商店里的插件。不过目前没精力搞了😂
