### ISSUE TITLE
自动刷新绑定YT视频上新提交的片段

### ISSUE THREAD

**Issue by NeKoOuO** [hanydd/BilibiliSponsorBlock#29]
現在有個狀況我不知道是bug才是本來就這樣 原本我的預期是載入這個影片的時候實時從YouTube上抓取片段
不過貌似我當初在綁定的時候沒有片段 那麼之後就算YouTube有增加 也不會出現在B站上
https://www.bilibili.com/video/BV1yFn9eNEgo/
![image](https://github.com/user-attachments/assets/09916328-765e-4307-bc73-e120f7b34296)

**Comment by NeKoOuO** [comment]
另外還有個小問題 就是綁定影片獲取到的片段是怎麼算的

**Comment by hanydd** [comment]
啊……这个功能确实是我还没做……主要之前绑视频的人比较少，我就搁置了，之后会加入自动刷新片段的。

**Comment by hanydd** [comment]
> 另外還有個小問題 就是綁定影片獲取到的片段是怎麼算的 還是說就只有紀錄綁定影片的數量

绑定视频同步过来的片段应该不算贡献的吧，我感觉肯定要和其他的片段分开计算，要不再加个field专门显示同步过来的片段数量

**Comment by hanydd** [comment]
如果现在想解决的话，就给绑定视频点个踩，再重新绑定就好了

**Comment by NeKoOuO** [comment]
> > 另外還有個小問題 就是綁定影片獲取到的片段是怎麼算的 還是說就只有紀錄綁定影片的數量
> 
> 绑定视频同步过来的片段应该不算贡献的吧，我感觉肯定要和其他的片段分开计算，要不再加个field专门显示同步过来的片段数量

不好吧 因為還是有不同的類型片段 如果只計算數量的話還是有點....

**Comment by hanydd** [comment]
Fixed by 6d845ef74c23ef41e178163e7ab6ad6f0580b647 and https://github.com/hanydd/BilibiliSponsorBlockServer/commit/425fd9e352a9cec15bc639c03eaf64d79789344a
