### ISSUE TITLE
新功能：允许在弹幕功能上标记恰饭开始的片段

### ISSUE THREAD

**Issue by MisteryMonster** [hanydd/BilibiliSponsorBlock#3]
弹幕里其实都已经有很多现成的 ”猝不及防&一拍即合&达成连击“提示，可以给弹幕点赞按钮的旁边设置一个片段开始和结束的按钮。在发送弹幕的时候也可以在旁边新增一个开始记录新片段的按钮

**Comment by HanYaodong** [comment]
合理！甚至可以直接根据弹幕内容自动生成一些片段。
不过这个功能工程量估计比较大，恐怕一时半会做不完😂

**Comment by lanytcc** [comment]
这个功能在推进吗？我可以帮忙，但是我不太熟悉项目，请告诉我从哪入手

**Comment by hanydd** [comment]
> 这个功能在推进吗？我可以帮忙，但是我不太熟悉项目，请告诉我从哪入手

目前还没有开发。如果想要开发的话，可以先去了解一下[Chrome插件](https://developer.chrome.com/docs/extensions)的运行逻辑。项目里目前所有功能的入口都在 [`content.ts`](https://github.com/hanydd/BilibiliSponsorBlock/blob/master/src/content.ts)
