### ISSUE TITLE
提交按鈕不符合邏輯

### ISSUE THREAD

**Issue by NeKoOuO** [hanydd/BilibiliSponsorBlock#34]
太反人類了 按到快紅溫了

https://github.com/user-attachments/assets/a1b1dda2-5f2d-4ace-951d-16937d8c0e90

**Comment by hanydd** [comment]
啊这，没想到改了下按钮会影响这里

**Comment by NeKoOuO** [comment]
不會改 放棄了：/

**Comment by hanydd** [comment]
刚好放反了😂马上发个版本修一下，今天晚上应该就能过
Fixed by e7cb6b14097c3854fba370b4a33bcc99748fdc45

**Comment by NeKoOuO** [comment]
按鈕現在有修了嗎

**Comment by hanydd** [comment]
修了，更新下0.3.3版本就好了
