### ISSUE TITLE
YT 按鈕無法正常顯示

### ISSUE THREAD

**Issue by NeKoOuO** [hanydd/BilibiliSponsorBlock#39]
0.3.3還是一樣

**Comment by hanydd** [comment]
你刷新页面把浏览器console里的报错发一下，我看你的container都插进去了，React没渲染

**Comment by NeKoOuO** [comment]
![image](https://github.com/user-attachments/assets/f4b8c46c-dc48-4650-80a4-7972674c4cc3)

**Comment by NeKoOuO** [comment]
![image](https://github.com/user-attachments/assets/59b3f4f2-252d-4b80-9ab5-787a3aa98600)

**Comment by hanydd** [comment]
好吧，并看不出什么…你截图里的错误是b站网站自己触发的，和什么登陆有关。所以你启动一个纯净无插件的chrome，也没法看到按钮吗？

**Comment by NeKoOuO** [comment]
對的 不管是乾淨的還是我平常用的都找不出問題

**Comment by hanydd** [comment]
Fixed by 538f222833fec57fc5bac569c51965da9a67c61f
import React没写对，我也不知道有什么区别（感谢chatGPT
