### ISSUE TITLE
提醒开发者，这个插件太影响B站的商业模式了，必被重点对待，开发者请保护好自己个人信息

### ISSUE THREAD

**Issue by NJYZ-96** [hanydd/BilibiliSponsorBlock#40]
使用了几天，体验太好了，无声无息的就跳过了广告。

有个预感是插件用户增多以后，必然被B站重点针对，如果技术手段无法屏蔽，B站多半会想办法召唤铁拳。

B站一直不愿意使用贴片硬广，采用目前的软广分成的形式，但现在的自动化插件对于这种商业模式是降维打击，B站必然不会坐视不理。如同之前李跳跳等一系列自动化跳过软件全被发律师函

目前的数据是通过用户提交的，算是一种低成本开源方案；后期B站可能通过技术手段大量污染数据，让体检变得极差。

**Comment by hanydd** [comment]
感谢提醒，希望阿B能够放PC端一马，也就占10%不到的流量🙊

**Comment by imtipi** [comment]
真被律师函把数据放出来然后停止运营就行，代码打包秽土转生，有问题去请教一下人家sponsorblock是怎么应对的就行
