### ISSUE TITLE
能正常使用，但是显示这个错误是什么原因？？

### ISSUE THREAD

**Issue by FUKUA2010** [hanydd/BilibiliSponsorBlock#45]
![2024_09_26_09_15_05](https://github.com/user-attachments/assets/9bf67240-15fe-48d2-93f3-16c7c0817f7e)
百分浏览器，Chromium 118.0.5993.159

**Comment by hanydd** [comment]
这个报错我只在插件更新的时候见到过。就是插件在后台更新版本了，但是当前页面还在尝试使用插件的功能，就会报这个错误。一般情况下刷新页面就好了，应该不影响使用。要是持续报错你可以继续反馈，我再去瞅瞅啥情况。

**Comment by FUKUA2010** [comment]
> 这个报错我只在插件更新的时候见到过。就是插件在后台更新版本了，但是当前页面还在尝试使用插件的功能，就会报这个错误。一般情况下刷新页面就好了，应该不影响使用。要是持续报错你可以继续反馈，我再去瞅瞅啥情况。

好的。
