### ISSUE TITLE
【功能】将提交过跳过的视频罗列展示

### ISSUE THREAD

**Issue by Jay5211** [hanydd/BilibiliSponsorBlock#50]
建议把提交过跳广告的视频罗列展示，提高利用率。可以在网站增加一个标签，网页内展示视频链接与提交人，使用次数等

**Comment by hanydd** [comment]
你说的类似这种吗？https://sb.ltn.fi/

**Comment by Jay5211** [comment]
> 你说的类似这种吗？https://sb.ltn.fi/

是的，提交者天南海北看的视频也不一样，可以列出来，互相提供便利

**Comment by hanydd** [comment]
这个之前也提过，我放到一个issue里面啦 #14

**Comment by hanydd** [comment]
http://47.103.74.95/
