### ISSUE TITLE
视频有分段的时候会挤压全屏按钮导致无法点击

### ISSUE THREAD

**Issue by AprDeci** [hanydd/BilibiliSponsorBlock#51]
就像图中一样,可以修改为如果有分段部分向左边挤压吗
![PixPin_2024-10-06_08-31-04](https://github.com/user-attachments/assets/ce38ff82-fe23-481f-8029-850428c6b3af)

**Comment by hanydd** [comment]
（拥挤的b站播放条😂

**Comment by AprDeci** [comment]
> （拥挤的b站播放条😂

发现不止是有分段的时候会发现这种情况,偶尔也会有普通视频全屏按键被挤压(应该也因为我还有其他插件在底部添加了元素.)
如果可以修改为鼠标进入该插件ICON区域再出现其他其他按钮或许会好一些.(现在的方案是.bpx-player-control-bottom-right整个区域会显示其他按钮,)
这样既可以无视挤压元素导致的问题也不会受位置偏移的影响.
