### ISSUE TITLE
[BUG] 在港澳台受限番剧的播放条上没有插件按钮

### ISSUE THREAD

**Issue by you-hengh** [hanydd/BilibiliSponsorBlock#55]
地址: https://www.bilibili.com/bangumi/play/ep840734
看不到视频控制条的按钮

![image](https://github.com/user-attachments/assets/c175176c-9da1-4bcc-8ebf-d4eadfe5e050)

**Comment by hanydd** [comment]
目前时候普通的视频插件才支持，番剧不支持

**Comment by hanydd** [comment]
duplicate of #49
