### ISSUE TITLE
提交失败

### ISSUE THREAD

**Issue by zxloveyyy** [hanydd/BilibiliSponsorBlock#56]
此请求无效 错误代码： 400 One of your segments times are invalid (too short, endTime before startTime, etc.)

**Comment by hanydd** [comment]
返回是说你提交的片段太短，或者有格式问题。能截个提交时候的图吗？

**Comment by zxloveyyy** [comment]
> 返回是说你提交的片段太短，或者有格式问题。能截个提交时候的图吗？

https://www.bilibili.com/video/BV13wx7edEow/?spm_id_from=333.1007.top_right_bar_window_history.content.click&vd_source=e5ba413251a0b4ed0f97a87e3fb15329

![微信截图_20241018191914](https://github.com/user-attachments/assets/503fdb93-9d3e-4b13-9e57-488c27e5be46)

**Comment by hanydd** [comment]
第二个片段没有结束时间啊，提交是所有一起提交的，有一个不合格的就通不过😂
