### ISSUE TITLE
【问题】看番时不会显示B站空降助手，且无法使用空降助手功能

### ISSUE THREAD

**Issue by Aarondongsq** [hanydd/BilibiliSponsorBlock#60]
此问题一直存在
![image](https://github.com/user-attachments/assets/cd42de03-1738-4a40-905c-a6c5f43ef59a)
番剧链接：https://www.bilibili.com/bangumi/play/ep1112394

**Comment by hanydd** [comment]
是的，如果需要可以到重复问题里留言 #49
