### ISSUE TITLE
【功能请求】请求增加第三方的【点赞、点踩、警告名单】功能

### ISSUE THREAD

**Issue by rurimiao** [hanydd/BilibiliSponsorBlock#61]
非常喜欢 BilibiliSponsorBlock 的空降指挥、视频标记等功能，意识到在这里实现一套第三方的、社会化的【点赞、点踩、警告名单】会是很自然、很简单的事情，因为已经有了全套的类似的 UI 交互、前后端逻辑和设施，所以提出这个功能请求。

> 前情提要：之前给 BiliScope 提过，不过似乎是它们缺乏后端设施和意愿，所以不打算做这个功能，https://github.com/gaogaotiantian/biliscope/issues/160

## 目前的【点赞、点踩】，实在没有什么社群意义。
- 各个平台都会隐藏点踩数。
- bilibili 限制网页端点踩。
- 平台的点赞、点踩，没有按照社群分组，所以水军刷的也会混入总的池子。

## 目前的【个体对 up 的黑名单】实在意义不大，应该有类似【社会化警告名单】的工具。
- 互联网很容易失去记忆或被篡改记忆。
    - 个人记录的黑名单无法分享给其它人作为参考，所以最好有一系列的【社会化警告名单】供大家订阅，而不是简单的个人拉黑了事。
    - 简单的关注、拉黑，无法对一个 up 的数据产生明显影响。
    - 简单的关注、拉黑，无法让人记住当时这么做的原因，有限的分组也只能简单缓解这个问题，最好允许关联一系列记录原因的条目，例如：x年月日y主播给z事件洗地。
- 只对 up 做黑名单过于简单粗暴。
    - 某个 up 的一个或一堆视频的好坏也无法完全决定它的另一个视频的好坏。
        - 应当允许单独标记：一个 up 是否有问题、一个视频的好坏、一个视频某段的好坏。
    - 平台会一刀切地【推送/不推送】黑名单视频。
        - 应当允许单独设定：是否永久不看某个 up 视频。

**Comment by hanydd** [comment]
我理解你说的是一个公开的点踩和拉黑名单？我不是特别支持这种东西，感觉很容易演化成为网暴。如果只是依赖投票来确定事实，那又怎么样保证不会被水军淹没呢？没有任何一个人是没有立场的，大家都会偏信自己本来就相信的东西，公开的表达对一件事的价值判断，容易演化成为互联网上的骂战……
