### ISSUE TITLE
视频播放完之后，进度条分段类别显示失效

### ISSUE THREAD

**Issue by giveup** [hanydd/BilibiliSponsorBlock#66]
视频：BV1XQDvYQEjn（或任意含有赞助的视频）
浏览器：Chrome 130.0.6723.117
插件版本：v. 0.4.0
Tampermonkey 5.3.2

复现步骤
1:以进度0开始播放视频
2:快速拖动至末尾

正常加载
<img width="764" alt="image" src="https://github.com/user-attachments/assets/af631289-0fde-43d5-a952-cbe20bd94b2a">

快速拖动至末尾，分段类别不显示
<img width="793" alt="image" src="https://github.com/user-attachments/assets/2fa5d2d7-c000-48b4-8ec9-3fd77f283d0b">

并且重新播放后（非刷新页面重新加载）也无法显示，但是可以正常跳过片段
<img width="752" alt="image" src="https://github.com/user-attachments/assets/e58327b1-bddb-415a-96fc-f699f4f64f3d">

<img width="769" alt="image" src="https://github.com/user-attachments/assets/01875e71-f088-432b-9799-ebad25704c0d">

**Comment by hanydd** [comment]
fixed by 7c6d4a2f12a1f39d56745cf432313499be5afc67
