### ISSUE TITLE
视频播放完之后，进度条最小化后分段类别显示失效

### ISSUE THREAD

**Issue by giveup** [hanydd/BilibiliSponsorBlock#74]
似乎未完全修复。
开始播放时，进度条最小化，此时分段类别能够正常显示。
<img width="765" alt="image" src="https://github.com/user-attachments/assets/adc626dc-711f-4d0a-845b-036fd1faf25e">

拖动进度条至末尾或播放完成后，会出现类似的问题。
<img width="760" alt="image" src="https://github.com/user-attachments/assets/e5242838-8c52-4d15-9d2d-3f6a9d18ced6">

但是现在插件已经更新到0.5.0，不确定之前是否有这样的问题。@hanydd

_Originally posted by @giveup in https://github.com/hanydd/BilibiliSponsorBlock/issues/66#issuecomment-2467338809_

**Comment by etherfun** [comment]
应该是个feature吧防止底部进度条被挡住 如下图 
进度已经到 "两" 字了但是悬浮进度条(图一)完全不知道在哪 但是底部进度条(图二)可以
而且悬浮进度条有刻意设置了z-index: 1这个css 底部没有这个
![image](https://github.com/user-attachments/assets/1b706d8e-44e9-4ff0-9141-455044e31c2c)
![image](https://github.com/user-attachments/assets/c62fb3e9-d833-4edf-b819-07c72110fc8c)

**Comment by hanydd** [comment]
咦原来这个也会变啊
