### ISSUE TITLE
【功能请求】能否添加在影视、番剧页面的跳过功能

### ISSUE THREAD

**Issue by TLSMars** [hanydd/BilibiliSponsorBlock#85]
希望加入在电影、电视剧页面的跳过功能，很多影视都有广告、过场/开场动画等，希望在这些页面添加跳过功能，例如[这个页面](https://www.bilibili.com/bangumi/play/ep1113410)，感谢！

**Comment by hanydd** [comment]
和#49重复了，之后在那里讨论就好😌
