### ISSUE TITLE
【新版BUG】选项出现两滚轮

### ISSUE THREAD

**Issue by Aarondongsq** [hanydd/BilibiliSponsorBlock#90]
如图：
![image](https://github.com/user-attachments/assets/521612aa-f4ff-421d-acb3-b3108b55c155)
版本为最新5.2，未启用鼠标缩放

**Comment by xiaoxuan010** [comment]
这个在 #87 应该是已经修复了，可以在最新版试试。

**Comment by Aarondongsq** [comment]
试了一下，Chrome 扩展商店上的还是不行

**Comment by xiaoxuan010** [comment]
> 试了一下，Chrome 扩展商店上的还是不行

修改还未正式上线应用商店，如果想要提前测试的话可以在 [Github Action](https://github.com/hanydd/BilibiliSponsorBlock/actions/runs/11973298833) 下载 [测试版](https://github.com/hanydd/BilibiliSponsorBlock/actions/runs/11973298833/artifacts/2224314993) 安装体验。

**Comment by Aarondongsq** [comment]
彳亍

**Comment by hanydd** [comment]
fixed by 6de7d3aaa455bc65096d863150b4d85cf5e55126
