### ISSUE TITLE
上一帧“,”和下一帧“.”按钮失效

### ISSUE THREAD

**Issue by admans** [hanydd/BilibiliSponsorBlock#96]
从昨天开始失效，按了没反应。
重启电脑也不行。
尝试更改快捷键也无效。

chrome 131.0.6778.86
B站空降助手 v. 0.5.2

**Comment by Talloran3999** [comment]
遇到了相同的问题

**Comment by etherfun** [comment]
https://github.com/hanydd/BilibiliSponsorBlock/blob/b0674be82c345c8c026266476c0ebecef2e617d3/src/utils/injectedScriptMessageUtils.ts#L33-L37
检查发现是`resolve(data.data as T); `返回了`undefined`
叔叔动API了?

**Comment by Aarondongsq** [comment]
举个爪，我也遇到了
